name: Update Blueprints

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 1

      - name: Change update_id and last_updated
        id: update_blueprint
        run: |
          FILES=(
            "blueprints/motion_light_blueprint.yaml"
          )

          CURRENT_DATE=$(date +"%Y-%m-%d %H:%M")
          COMMIT_MSG_BODY="Updated blueprints:"

          for FILE in "${FILES[@]}"; do
            echo "Processing $FILE..."
            if [ ! -f "$FILE" ]; then
              echo "Warning: $FILE not found, skipping."
              continue
            fi

            if ! grep -q "^  update_id: " "$FILE"; then
              echo "Warning: update_id not found in $FILE, skipping."
              continue
            fi

            NEW_UUID=$(cat /proc/sys/kernel/random/uuid)

            sed -i "s/^  update_id: .*/  update_id: $NEW_UUID/" "$FILE"
            sed -i "s/^  last_updated: .*/  last_updated: \"$CURRENT_DATE\"/" "$FILE"

            COMMIT_MSG_BODY="$COMMIT_MSG_BODY\n- $FILE: $NEW_UUID ($CURRENT_DATE)"
            echo "Updated $FILE with ID $NEW_UUID"
          done

          echo "FILES=${FILES[*]}" >> $GITHUB_OUTPUT

          {
            echo "COMMIT_MSG_BODY<<EOF"
            echo -e "$COMMIT_MSG_BODY"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          for FILE in ${{ steps.update_blueprint.outputs.FILES }}; do
            git add "$FILE"
          done

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update blueprints" -m "${{ steps.update_blueprint.outputs.COMMIT_MSG_BODY }}"
            git pull --rebase origin main
            git push origin main
          fi
