blueprint:
  name: Motion-Activated Light/Switch (Frequent Updates)
  description: A simple blueprint that turns on a light or switch when motion is detected and turns it off when motion stops. This file is updated frequently to simulate new releases.
  author: luuquangvu
  domain: automation
  source_url: https://github.com/luuquangvu/demo-blueprints/blob/main/blueprints/motion_light_blueprint.yaml
  homeassistant:
    min_version: 2024.12.0
  input:
    motion_sensor:
      name: Motion Sensor
      description: The binary sensor that detects motion.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_entity:
      name: Target Light/Switch
      description: The light or switch to control.
      selector:
        target:
          entity:
            domain:
              - light
              - switch

mode: single
max_exceeded: silent
variables:
  update_id: c6ce7ac5-6651-46d4-8992-3d49f40d3c4e
  last_updated: "2026-03-28 22:45"

triggers:
  - trigger: state
    entity_id: !input motion_sensor
    from:
      - "on"
      - "off"
    to:
      - "off"
      - "on"
actions:
  - action: "homeassistant.turn_{{ trigger.to_state.state }}"
    target: !input target_entity
