blueprint:
  name: Motion-Activated Light/Switch (Frequent Updates)
  description: |-
    A simple blueprint that turns on a light or switch when motion is detected and turns it off when motion stops. This file is updated frequently to simulate new releases.

    Changelog:
    - Phase 3/4: Changed device_class to motion
      device_class: motion
      update_id: d6523487-a8a1-46ec-a3da-e9ff560a520e
      updated: 2026-08-29 04:43 UTC
  author: luuquangvu
  domain: automation
  source_url: https://github.com/luuquangvu/demo-blueprints/blob/main/blueprints/motion_light_blueprint.yaml
  homeassistant:
    min_version: 2024.12.0
  input:
    motion_sensor:
      name: Motion Sensor
      description: The binary sensor that detects motion.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_entity:
      name: Target Light/Switch
      description: The light or switch to control.
      selector:
        target:
          entity:
            domain:
              - light
              - switch

mode: single
max_exceeded: silent
variables:
  update_id: d6523487-a8a1-46ec-a3da-e9ff560a520e
  last_updated: "2026-08-29 04:43 UTC"

triggers:
  - trigger: state
    entity_id: !input motion_sensor
    from:
      - "on"
      - "off"
    to:
      - "off"
      - "on"
actions:
  - action: "homeassistant.turn_{{ trigger.to_state.state }}"
    target: !input target_entity
